schema_version = "1.0.0"

id = "fast_splatting"
version = "0.6.1"
name = "Fast Splatting"
tagline = "High-performance 3D Gaussian Splatting viewer embedded in Blender's viewport"
maintainer = "Kazama666"
type = "add-on"

website = "https://github.com/kazama666/FastSplatting"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["3D View"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

